# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-11-16 22:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='friendships',
            field=models.ManyToManyField(related_name='_user_friendships_+', to='books.User'),
        ),
    ]
